version: "3.8"

services:
  mariadb:
    container_name: "MariaDB"
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
